- id: export-requirements
  name: poetry-export-requirements
  entry: poetry-export-requirements
  language: python
  files: "pyproject.toml"
  pass_filenames: false

- id: export-dev-requirements
  name: poetry-export-dev-requirements
  entry: poetry-export-requirements --dev
  language: python
  files: "pyproject.toml"
  pass_filenames: false
