[tool.black]
line-length = 80

[tool.isort]
line_length = 80

[tool.semantic_release]
version_variable = "hooks/__init__.py:__version__"
upload_to_pypi = false
upload_to_release = false
commit_parser = "semantic_release.history.angular_parser"
